// Module builder for creating Foundry VTT module structure

export interface ModuleConfig {
    id: string;
    title: string;
    description: string;
    version: string;
    author: string;
}

export class ModuleBuilder {
    
    /**
     * Generate the module.json file
     */
    static generateModuleJson(config: ModuleConfig): string {
        const moduleData = {
            id: config.id,
            title: config.title,
            description: config.description,
            version: config.version,
            compatibility: {
                minimum: "11",
                verified: "11"
            },
            authors: [
                {
                    name: config.author
                }
            ],
            packs: [
                {
                    name: "creatures",
                    label: "Creatures",
                    path: "packs/creatures.db",
                    type: "Actor",
                    system: "dnd5e",
                    ownership: {
                        PLAYER: "OBSERVER",
                        ASSISTANT: "OWNER"
                    }
                }
            ],
            packFolders: [
                {
                    name: "Obsidian Import",
                    sorting: "a",
                    packs: ["creatures"]
                }
            ],
            manifest: `https://example.com/modules/${config.id}/module.json`,
            download: `https://example.com/modules/${config.id}/${config.id}.zip`,
            relationships: {
                systems: [
                    {
                        id: "dnd5e",
                        type: "system",
                        compatibility: {
                            minimum: "3.0.0"
                        }
                    }
                ]
            }
        };
        
        return JSON.stringify(moduleData, null, 2);
    }
    
    /**
     * Generate the compendium database file in LevelDB format
     */
    static generateCompendiumDB(actors: any[]): string {
        // Generate LevelDB-style entries for each actor
        const entries: string[] = [];
        
        actors.forEach((actor, index) => {
            const id = this.generateId();
            
            // Create the actor entry with proper Foundry structure
            const entry = {
                _id: id,
                name: actor.name,
                type: actor.type,
                img: "icons/svg/mystery-man.svg",
                system: actor.system,
                items: actor.items,
                effects: actor.effects || [],
                folder: null as null,
                sort: index * 100000,
                ownership: {
                    default: 0
                },
                flags: actor.flags || {},
                _stats: {
                    systemId: "dnd5e",
                    systemVersion: "3.0.0",
                    coreVersion: "11.315",
                    createdTime: Date.now(),
                    modifiedTime: Date.now(),
                    lastModifiedBy: "obsidian-exporter"
                }
            };
            
            entries.push(JSON.stringify(entry));
        });
        
        // Join entries with newlines (LevelDB format)
        return entries.join('\n');
    }
    
    /**
     * Generate a unique ID for Foundry documents
     */
    private static generateId(): string {
        return 'xxxxxxxxxxxxxxxx'.replace(/x/g, () => {
            return (Math.random() * 16 | 0).toString(16);
        });
    }
    
    /**
     * Create the complete module structure
     */
    static createModuleStructure(config: ModuleConfig, actors: any[]): { [filename: string]: string } {
        const files: { [filename: string]: string } = {};
        
        // Generate module.json
        files['module.json'] = this.generateModuleJson(config);
        
        // Generate compendium database
        files['packs/creatures.db'] = this.generateCompendiumDB(actors);
        
        // Generate README
        files['README.md'] = this.generateReadme(config, actors.length);
        
        return files;
    }
    
    /**
     * Generate README file
     */
    private static generateReadme(config: ModuleConfig, actorCount: number): string {
        return `# ${config.title}

${config.description}

## Contents

This module contains ${actorCount} creature(s) imported from Obsidian.

## Installation

1. Download the module zip file
2. Extract to your Foundry VTT \`Data/modules\` folder
3. Enable the module in your world's Module Management
4. Find the creatures in the "Creatures" compendium

## Version

${config.version}

## Author

${config.author}

## System

This module is designed for the D&D 5e system.

---

*Generated by Foundry VTT Exporter for Obsidian*
`;
    }
}
